"""Dependency-free reporting helpers: CSV, LaTeX tables and SVG figures.

Figures are emitted as hand-written SVG so that the whole experimental pipeline
runs on a bare CPython installation; the paper includes them directly.
"""

from __future__ import annotations

import csv
import os
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

PALETTE = ["#1f4e79", "#c0504d", "#4f81bd", "#9bbb59", "#8064a2", "#f79646", "#4bacc6"]
INK = "#222222"
GRID = "#d9d9d9"


def ensure_dir(path: str) -> str:
    os.makedirs(path, exist_ok=True)
    return path


def write_csv(path: str, header: Sequence[str], rows: Iterable[Sequence[object]]) -> str:
    ensure_dir(os.path.dirname(path))
    with open(path, "w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(header)
        for r in rows:
            w.writerow(list(r))
    return path


def _tex_escape(value: object) -> str:
    """Escape a data cell. The arrow U+2192 is the one character allowed to
    carry meaning: it is rendered as math, so path cells read as paths."""
    text = str(value)
    for a, b in (("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("$", r"\$"),
                 ("#", r"\#"), ("_", r"\_"), ("{", r"\{"), ("}", r"\}"), ("~", r"\textasciitilde{}"),
                 ("^", r"\textasciicircum{}")):
        text = text.replace(a, b)
    return text.replace("\u2192", "$\\to$")


def write_latex_table(
    path: str,
    header: Sequence[str],
    rows: Iterable[Sequence[object]],
    caption: str,
    label: str,
    align: Optional[str] = None,
    note: str = "",
    star: bool = False,
) -> str:
    ensure_dir(os.path.dirname(path))
    rows = list(rows)
    align = align or ("l" + "r" * (len(header) - 1))
    env = "table*" if star else "table"
    lines = [
        "% generated by the CAPM pipeline -- do not edit by hand",
        "\\begin{" + env + "}[t]",
        "\\centering",
        "\\caption{" + caption + "}",
        "\\label{" + label + "}",
        "\\capmtablefont",
        "\\begin{tabular}{" + align + "}",
        "\\toprule",
        # headers are author-provided LaTeX (they may contain math); only the
        # data cells are escaped
        " & ".join(str(h) for h in header) + " \\\\",
        "\\midrule",
    ]
    for r in rows:
        lines.append(" & ".join(_tex_escape(c) for c in r) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    if note:
        lines.append("\\\\[2pt]\\footnotesize " + note)
    lines.append("\\end{" + env + "}")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    return path


# --------------------------------------------------------------------------
# SVG primitives
# --------------------------------------------------------------------------

def _svg_header(width: int, height: int, title: str) -> List[str]:
    return [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}" font-family="Helvetica,Arial,sans-serif">',
        f'<title>{_xml(title)}</title>',
        f'<rect width="{width}" height="{height}" fill="#ffffff"/>',
    ]


def _xml(text: object) -> str:
    return (str(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def barh_chart(
    path: str,
    labels: Sequence[str],
    values: Sequence[float],
    title: str,
    xlabel: str = "",
    value_fmt: str = "{:.3f}",
    width: int = 900,
    bar_h: int = 26,
    left: int = 330,
    color: Optional[str] = None,
) -> str:
    ensure_dir(os.path.dirname(path))
    n = len(labels)
    top, bottom = 56, 46
    height = top + n * bar_h + bottom
    vmax = max(values) if values and max(values) > 0 else 1.0
    plot_w = width - left - 90
    out = _svg_header(width, height, title)
    out.append(f'<text x="18" y="30" font-size="17" font-weight="600" fill="{INK}">{_xml(title)}</text>')
    for i in range(5):
        x = left + plot_w * i / 4.0
        out.append(f'<line x1="{x:.1f}" y1="{top - 8}" x2="{x:.1f}" y2="{top + n * bar_h}" '
                   f'stroke="{GRID}" stroke-width="1"/>')
        out.append(f'<text x="{x:.1f}" y="{top + n * bar_h + 18}" font-size="11" '
                   f'text-anchor="middle" fill="#666">{value_fmt.format(vmax * i / 4.0)}</text>')
    for i, (lab, val) in enumerate(zip(labels, values)):
        y = top + i * bar_h
        w = plot_w * (val / vmax) if vmax else 0
        col = color or PALETTE[i % len(PALETTE)] if color is None else color
        out.append(f'<rect x="{left}" y="{y + 4}" width="{max(w, 0.5):.1f}" height="{bar_h - 9}" '
                   f'fill="{col}" fill-opacity="0.88"/>')
        out.append(f'<text x="{left - 10}" y="{y + bar_h / 2 + 4:.0f}" font-size="12" '
                   f'text-anchor="end" fill="{INK}">{_xml(lab)}</text>')
        out.append(f'<text x="{left + w + 8:.1f}" y="{y + bar_h / 2 + 4:.0f}" font-size="11" '
                   f'fill="#444">{value_fmt.format(val)}</text>')
    if xlabel:
        out.append(f'<text x="{left + plot_w / 2:.0f}" y="{height - 8}" font-size="12" '
                   f'text-anchor="middle" fill="#444">{_xml(xlabel)}</text>')
    out.append("</svg>")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
    return path


def grouped_bar_chart(
    path: str,
    categories: Sequence[str],
    series: Sequence[Tuple[str, Sequence[float]]],
    title: str,
    ylabel: str = "",
    value_fmt: str = "{:.1f}",
    width: int = 900,
    height: int = 420,
) -> str:
    ensure_dir(os.path.dirname(path))
    left, right, top, bottom = 70, 24, 64, 76
    plot_w, plot_h = width - left - right, height - top - bottom
    vmax = max((max(v) for _, v in series if len(v)), default=1.0) or 1.0
    vmax *= 1.15
    out = _svg_header(width, height, title)
    out.append(f'<text x="18" y="28" font-size="17" font-weight="600" fill="{INK}">{_xml(title)}</text>')
    for i in range(5):
        y = top + plot_h - plot_h * i / 4.0
        out.append(f'<line x1="{left}" y1="{y:.1f}" x2="{left + plot_w}" y2="{y:.1f}" stroke="{GRID}"/>')
        out.append(f'<text x="{left - 8}" y="{y + 4:.1f}" font-size="11" text-anchor="end" '
                   f'fill="#666">{value_fmt.format(vmax * i / 4.0)}</text>')
    gw = plot_w / max(len(categories), 1)
    bw = gw * 0.78 / max(len(series), 1)
    for ci, cat in enumerate(categories):
        gx = left + ci * gw
        for si, (name, vals) in enumerate(series):
            v = vals[ci] if ci < len(vals) else 0.0
            h = plot_h * (v / vmax)
            x = gx + gw * 0.11 + si * bw
            out.append(f'<rect x="{x:.1f}" y="{top + plot_h - h:.1f}" width="{bw * 0.9:.1f}" '
                       f'height="{max(h, 0.5):.1f}" fill="{PALETTE[si % len(PALETTE)]}" fill-opacity="0.9"/>')
        out.append(f'<text x="{gx + gw / 2:.1f}" y="{top + plot_h + 18}" font-size="11" '
                   f'text-anchor="middle" fill="{INK}">{_xml(cat)}</text>')
    for si, (name, _) in enumerate(series):
        lx = left + si * 190
        out.append(f'<rect x="{lx}" y="{height - 30}" width="12" height="12" '
                   f'fill="{PALETTE[si % len(PALETTE)]}"/>')
        out.append(f'<text x="{lx + 18}" y="{height - 19}" font-size="12" fill="{INK}">{_xml(name)}</text>')
    if ylabel:
        out.append(f'<text x="16" y="{top + plot_h / 2:.0f}" font-size="12" fill="#444" '
                   f'transform="rotate(-90 16 {top + plot_h / 2:.0f})" text-anchor="middle">{_xml(ylabel)}</text>')
    out.append("</svg>")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
    return path


def line_chart(
    path: str,
    series: Sequence[Tuple[str, Sequence[Tuple[float, float]]]],
    title: str,
    xlabel: str = "",
    ylabel: str = "",
    width: int = 860,
    height: int = 420,
    x_fmt: str = "{:.0f}",
    y_fmt: str = "{:.1f}",
) -> str:
    ensure_dir(os.path.dirname(path))
    left, right, top, bottom = 76, 28, 64, 76
    plot_w, plot_h = width - left - right, height - top - bottom
    xs = [x for _, pts in series for x, _ in pts] or [0.0, 1.0]
    ys = [y for _, pts in series for _, y in pts] or [0.0, 1.0]
    xmin, xmax = min(xs), max(xs)
    ymin, ymax = 0.0, max(ys) * 1.12 or 1.0
    if xmax == xmin:
        xmax = xmin + 1.0

    def px(x: float) -> float:
        return left + plot_w * (x - xmin) / (xmax - xmin)

    def py(y: float) -> float:
        return top + plot_h - plot_h * (y - ymin) / (ymax - ymin)

    out = _svg_header(width, height, title)
    out.append(f'<text x="18" y="28" font-size="17" font-weight="600" fill="{INK}">{_xml(title)}</text>')
    for i in range(5):
        y = top + plot_h - plot_h * i / 4.0
        out.append(f'<line x1="{left}" y1="{y:.1f}" x2="{left + plot_w}" y2="{y:.1f}" stroke="{GRID}"/>')
        out.append(f'<text x="{left - 8}" y="{y + 4:.1f}" font-size="11" text-anchor="end" '
                   f'fill="#666">{y_fmt.format(ymax * i / 4.0)}</text>')
        x = left + plot_w * i / 4.0
        out.append(f'<text x="{x:.1f}" y="{top + plot_h + 18}" font-size="11" text-anchor="middle" '
                   f'fill="#666">{x_fmt.format(xmin + (xmax - xmin) * i / 4.0)}</text>')
    for si, (name, pts) in enumerate(series):
        col = PALETTE[si % len(PALETTE)]
        d = " ".join(("M" if i == 0 else "L") + f"{px(x):.1f},{py(y):.1f}" for i, (x, y) in enumerate(pts))
        out.append(f'<path d="{d}" fill="none" stroke="{col}" stroke-width="2.4"/>')
        for x, y in pts:
            out.append(f'<circle cx="{px(x):.1f}" cy="{py(y):.1f}" r="3.2" fill="{col}"/>')
        lx = left + si * 200
        out.append(f'<rect x="{lx}" y="{height - 30}" width="12" height="12" fill="{col}"/>')
        out.append(f'<text x="{lx + 18}" y="{height - 19}" font-size="12" fill="{INK}">{_xml(name)}</text>')
    if xlabel:
        out.append(f'<text x="{left + plot_w / 2:.0f}" y="{top + plot_h + 42}" font-size="12" '
                   f'text-anchor="middle" fill="#444">{_xml(xlabel)}</text>')
    if ylabel:
        out.append(f'<text x="16" y="{top + plot_h / 2:.0f}" font-size="12" fill="#444" '
                   f'transform="rotate(-90 16 {top + plot_h / 2:.0f})" text-anchor="middle">{_xml(ylabel)}</text>')
    out.append("</svg>")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
    return path
